spring:
  application:
    name: workday
  profiles:
    active: prod
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
pagehelper:
  auto-dialect: true
  close-conn: false
  reasonable: true
    
eureka:
  instance:
    preferIpAddress: true
---
spring:
  profiles: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.90.110:1521/ORCL
    username: APP_BASE
    password: APP_BASE
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@122.224.140.202:1521:SYS
    username: APP_BASE
    password: APP_BASE
    
---
spring:
  profiles: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.100.32.61:1521/SYG
    username: APP_BASE
    password: APP_BASE
  thymeleaf:
    cache: true
    
sso: 
  server: 
    host-url: http://10.100.32.59/sso-auth
    login-url: http://10.100.32.59/portal-server/login/login.jsp
  client:
    host-url: http://10.100.32.66:8080
    orm-url: http://10.100.32.66/orm
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.100.32.197:8000/eureka/,http://10.100.32.192:8000/eureka/,http://10.100.32.130:8000/eureka/
